server.port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petshop
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update #create-drop, none, update, validate
  jpa.show-sql: true
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging.level:
  org.hibernate.SQL: DEBUG